
   Name           Domain             Range
   ----------------------------------------
   mult           <x,.1>             .2
   ----------------------------------------
   add            <.3,.2>            .4
   ----------------------------------------
   mult           <x,.4>             .5
   ----------------------------------------
   add            <.6,.5>            .7
   ----------------------------------------
   mult           <x,.7>             .8
   ----------------------------------------
   add            <.9,.8>            .10
   ----------------------------------------

 Directions -  <<in,in,in>,in> ~ out

 Wiring -  <<.9,.6,.3>,.1> ~ .10

 Inputs -  .9 .6 .3 .1
