
   Name           Domain             Range
   ----------------------------------------
   mult           <.1,.2>            .3
   ----------------------------------------

 Directions -  <in,in> ~ <<in,in>,out>

 Wiring -  <.1,.2> ~ <<.1,.2>,.3>

 Inputs -  .1 .2
