
   Name           Domain             Range
   ----------------------------------------
   add            <.1,.2>            .3
   ----------------------------------------
   add            <.4,.3>            .5
   ----------------------------------------

 Directions -  <in,<in,in>> ~ out

 Wiring -  <.4,<.1,.2>> ~ .5

 Inputs -  .4 .1 .2
