
   Name           Domain             Range
   ----------------------------------------
   mult           <.1,.2>            .3
   mult           <.1,.4>            .5
   mult           <.1,.6>            .7
   mult           <.1,.8>            .9
   mult           <.1,.10>           .11
   mult           <.1,.12>           .13
   mult           <.1,.14>           .15
   ----------------------------------------
   mult           <.1,.5>            .16
   mult           <.1,.7>            .17
   mult           <.1,.9>            .18
   mult           <.1,.11>           .19
   mult           <.1,.13>           .20
   mult           <.1,.15>           .21
   add            <.22,.3>           .23
   ----------------------------------------
   mult           <.1,.17>           .24
   mult           <.1,.18>           .25
   mult           <.1,.19>           .26
   mult           <.1,.20>           .27
   mult           <.1,.21>           .28
   ----------------------------------------
   mult           <.1,.25>           .29
   mult           <.1,.26>           .30
   mult           <.1,.27>           .31
   mult           <.1,.28>           .32
   add            <.16,.24>          .33
   ----------------------------------------
   mult           <.1,.30>           .34
   mult           <.1,.31>           .35
   mult           <.1,.32>           .36
   add            <.23,.33>          .37
   ----------------------------------------
   mult           <.1,.35>           .38
   mult           <.1,.36>           .39
   add            <.29,.34>          .40
   ----------------------------------------
   mult           <.1,.39>           .41
   ----------------------------------------
   add            <.38,.41>          .42
   ----------------------------------------
   add            <.40,.42>          .43
   ----------------------------------------
   add            <.37,.43>          .44
   ----------------------------------------

 Directions -  <in,<in,in,in,in,in,in,in,in>> ~ out

 Wiring -  <.1,<.22,.2,.4,.6,.8,.10,.12,.14>> ~ .44

 Inputs -  .1 .22 .2 .4 .6 .8 .10 .12 .14
